package:
  name: classix
  version: 0.7.9


source:
  fn: classixclustering-0.7.9.tar.gz
  url: https://files.pythonhosted.org/packages/f8/9e/c5214489eb6801c746792e38f7ea3a282e62cad3c23db310a1e13be2803a/classixclustering-0.7.9.tar.gz
  sha256: 680b5d45d436665e2f0aec4d43218408532a0e84a4c25c341670ec7dbc3faede


build:
  noarch: python
  number: 1

requirements:
  build:
    - python >=3.6
    - pip
    - setuptools
    - pandas
    - numpy 
    - requests
    - cython
    - scipy
    - matplotlib

  host:
    - python >=3.6
    - setuptools
    - pandas
    - numpy 
    - requests
    - cython
    - scipy
    - matplotlib

  run:
    - python >=3.6


test:
  requires:
    - pip
    - numpy
    - scipy
    - requests
    - pandas
    - matplotlib
  files:
    - runtest.py
  imports:
    - classix
    - numpy
  commands:
    - pip check


about:
  home: https://github.com/nla-group/classix
  summary: 'CLASSIX is a fast and explainable clustering algorithm based on sorting.'
  license: MIT
  license_family: MIT
  license_file: LICENSE
  dev_url: https://github.com/nla-group/classix

extra:
  recipe-maintainers:
    - chenxinye
    - guettel
